apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r1d930134-java-springboot
  janus-idp.io/tekton: r1d930134-java-springboot
  backstage.io/kubernetes-id: r1d930134-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r1d930134-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
